name: ecom

services:
    postgresdb:
        image: "postgres:alpine"
        container_name: "postgres"
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase
        ports:
            - "5431:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

# Added external volume for postgres data persistence
volumes:
    postgres_data:
